[2025-01-31T01:32:18.122+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T01:32:18.135+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: primeira_dag.tsk2 manual__2025-01-31T01:32:09.501503+00:00 [queued]>
[2025-01-31T01:32:18.140+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: primeira_dag.tsk2 manual__2025-01-31T01:32:09.501503+00:00 [queued]>
[2025-01-31T01:32:18.140+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T01:32:18.147+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): tsk2> on 2025-01-31 01:32:09.501503+00:00
[2025-01-31T01:32:18.153+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'primeira_dag', 'tsk2', 'manual__2025-01-31T01:32:09.501503+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/primeira_dag.py', '--cfg-path', '/tmp/tmp7t601m5o']
[2025-01-31T01:32:18.156+0000] {standard_task_runner.py:105} INFO - Job 21: Subtask tsk2
[2025-01-31T01:32:18.152+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2992) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T01:32:18.156+0000] {standard_task_runner.py:72} INFO - Started process 2993 to run task
[2025-01-31T01:32:18.196+0000] {task_command.py:467} INFO - Running <TaskInstance: primeira_dag.tsk2 manual__2025-01-31T01:32:09.501503+00:00 [running]> on host 15928652fac1
[2025-01-31T01:32:18.239+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='primeira_dag' AIRFLOW_CTX_TASK_ID='tsk2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T01:32:09.501503+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T01:32:09.501503+00:00'
[2025-01-31T01:32:18.239+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T01:32:18.250+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-31T01:32:18.250+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', "sleep 5; echo 'Hello World from Task 1'"]
[2025-01-31T01:32:18.256+0000] {subprocess.py:99} INFO - Output:
[2025-01-31T01:32:23.271+0000] {subprocess.py:106} INFO - Hello World from Task 1
[2025-01-31T01:32:23.275+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-31T01:32:23.319+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T01:32:23.320+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=primeira_dag, task_id=tsk2, run_id=manual__2025-01-31T01:32:09.501503+00:00, execution_date=20250131T013209, start_date=20250131T013218, end_date=20250131T013223
[2025-01-31T01:32:23.346+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T01:32:23.367+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-31T01:32:23.368+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
