[2025-01-31T01:48:05.974+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T01:48:05.985+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quarta_dag.tsk2 manual__2025-01-31T01:47:57.962187+00:00 [queued]>
[2025-01-31T01:48:05.990+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quarta_dag.tsk2 manual__2025-01-31T01:47:57.962187+00:00 [queued]>
[2025-01-31T01:48:05.990+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T01:48:05.997+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): tsk2> on 2025-01-31 01:47:57.962187+00:00
[2025-01-31T01:48:06.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3267) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T01:48:06.004+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'quarta_dag', 'tsk2', 'manual__2025-01-31T01:47:57.962187+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/quarta_dag.py', '--cfg-path', '/tmp/tmp4gj_p602']
[2025-01-31T01:48:06.007+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask tsk2
[2025-01-31T01:48:06.006+0000] {standard_task_runner.py:72} INFO - Started process 3268 to run task
[2025-01-31T01:48:06.045+0000] {task_command.py:467} INFO - Running <TaskInstance: quarta_dag.tsk2 manual__2025-01-31T01:47:57.962187+00:00 [running]> on host 15928652fac1
[2025-01-31T01:48:06.091+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='quarta_dag' AIRFLOW_CTX_TASK_ID='tsk2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T01:47:57.962187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T01:47:57.962187+00:00'
[2025-01-31T01:48:06.092+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T01:48:06.102+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-31T01:48:06.103+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-01-31T01:48:06.112+0000] {subprocess.py:99} INFO - Output:
[2025-01-31T01:48:11.121+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-31T01:48:11.171+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T01:48:11.174+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=quarta_dag, task_id=tsk2, run_id=manual__2025-01-31T01:47:57.962187+00:00, execution_date=20250131T014757, start_date=20250131T014805, end_date=20250131T014811
[2025-01-31T01:48:11.230+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T01:48:11.246+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T01:48:11.247+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
