[2025-01-31T01:40:44.746+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T01:40:44.765+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: terceira_dag.tsk3 manual__2025-01-31T01:40:35.689613+00:00 [queued]>
[2025-01-31T01:40:44.770+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: terceira_dag.tsk3 manual__2025-01-31T01:40:35.689613+00:00 [queued]>
[2025-01-31T01:40:44.771+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T01:40:44.778+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): tsk3> on 2025-01-31 01:40:35.689613+00:00
[2025-01-31T01:40:44.788+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3157) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T01:40:44.789+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'terceira_dag', 'tsk3', 'manual__2025-01-31T01:40:35.689613+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/terceira_dag.py', '--cfg-path', '/tmp/tmpyszigi_m']
[2025-01-31T01:40:44.792+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask tsk3
[2025-01-31T01:40:44.792+0000] {standard_task_runner.py:72} INFO - Started process 3158 to run task
[2025-01-31T01:40:44.857+0000] {task_command.py:467} INFO - Running <TaskInstance: terceira_dag.tsk3 manual__2025-01-31T01:40:35.689613+00:00 [running]> on host 15928652fac1
[2025-01-31T01:40:44.920+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='terceira_dag' AIRFLOW_CTX_TASK_ID='tsk3' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T01:40:35.689613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T01:40:35.689613+00:00'
[2025-01-31T01:40:44.921+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T01:40:44.934+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-31T01:40:44.936+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2025-01-31T01:40:44.945+0000] {subprocess.py:99} INFO - Output:
[2025-01-31T01:40:49.956+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-31T01:40:50.010+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T01:40:50.012+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=terceira_dag, task_id=tsk3, run_id=manual__2025-01-31T01:40:35.689613+00:00, execution_date=20250131T014035, start_date=20250131T014044, end_date=20250131T014050
[2025-01-31T01:40:50.079+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T01:40:50.096+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T01:40:50.097+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
